# Site
name: "Hello!"
title: "Welcome FHL!"
description: "My github blog"
logo: 'assets/images/4leaves.jpg'
favicon: 'assets/images/sigNet1.png'
# baseurl: /
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: ''
# include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: robert
    display_name: robert
    avatar: assets/images/4leaves.png
    email: robert.fh.li@gmail.com
    web: https://fuhaililab@github.io
    # twitter: https://twitter.com/wowthemesnet
    description: "I am Robert Li"
  william:
    name: William
    display_name: William    
    avatar: 'assets/images/sigNet1.png'
    # gravatar: 
    email: robert.fh.li@gmail.com
    # web: 
    # twitter: 
    # description: "I am William"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# exclude: [changelog.md, LICENSE.txt, Gemfile, Gemfile.lock]
